### PR TITLE
Leave boost filesystem

### PR DESCRIPTION
**Pull request by boxanm**
# Description

### Summary:
Minor changes to the docs (mostly replacing old eth links with norlab).
I removed the `boost::filesystem` dependency completely from libpointmatcher and replaced it with the equivalent `std::filesystem`. Some of the boost methods have been deprecated for a long time and started causing compilation issues and unexpected behaviors on newer platforms.

### Changes and type of changes (quick overview):

- Update docs links
- Remove the `boost::filesystem` dependency

---

# Checklist:

### Code related

- [x] I have made corresponding changes to the documentation 
      (i.e.: function, class, script header, README.md)
- [x] I have commented hard-to-understand code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] All tests pass locally with my changes 
      (Check [contributing_instructions.md](/doc/contributing/contributing_instructions.md) for local testing procedure using _libpointmatcher-build-system_)

### PR creation related

- [x] My pull request `base ref` branch is set to the `develop` branch 
     (the _build-system_ won't be triggered otherwise)
- [x] My pull request branch is up-to-date with the `develop` branch 
     (the _build-system_ will reject it otherwise)

### PR description related

- [x] I have included a quick summary of the changes
- [x] I have indicated the related issue's id with `# <issue-id>` if changes are of type `fix`
- [x] I have included a high-level list of changes and their corresponding types
      (See [commit_msg_reference.md](/doc/contributing/commit_msg_reference.md) for details)

---

### CODE REVIEW

**Review by simonpierredeschenes — APPROVED** [review]

**Comment by boxanm** [comment]
The build is failing on Bionic because we have an outdated compiler. [This thread](https://askubuntu.com/questions/1256440/how-to-get-libstdc-with-c17-filesystem-headers-on-ubuntu-18-bionic) has an explanation.
@RedLeader962 can you add these lines to the Bionic's Dockerfile?
```shell
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install gcc-9 g++-9
```

**Comment by RedLeader962** [comment]
@boxanm Does it mean that we can drop the Boost install step from `build_system/ubuntu/lpm_install_dependencies_general_ubuntu.bash` or is it required for other dependencies?

```shell
n2st::teamcity_service_msg_blockOpened "Install Libpointmatcher dependencies › Boost"
# https://www.boost.org/doc/libs/1_79_0/more/getting_started/unix-variants.html

sudo apt-get update &&
  sudo apt-get install --assume-yes "${APT_FLAGS[@]}" \
    libboost-all-dev &&
  sudo rm -rf /var/lib/apt/lists/*

n2st::teamcity_service_msg_blockClosed
```

**Comment by RedLeader962** [comment]
@boxanm So updating the LPM dependencies is a two steps process:
1. rebuild and push the dependencies to dockerhub
2. build and test the current PR.

I'm updating the build system dependencies install script in a separate branch `dev-build-add-bionic-specific-gcc-install-requirement--nmo-585`.
The dependencies are rebuilding at the moment and I've programmed a remote run for your PR branch that will start right after the dependencies are done re-building. 
I'll keep you posted

**Comment by boxanm** [comment]
@RedLeader962 We still need boost for other stuff, for now I just replaced the broken dependency on boost::filesystem. Eventually I'd like to remove boost completely but that might be a longer project.

**Review by RedLeader962 — APPROVED** [review]

**Comment by RedLeader962** [comment]
@boxanm `dev-build-add-bionic-specific-gcc-install-requirement--nmo-585` PR #583 has passed and is now merge in develop. Subsequent remote run of the `[leave-boost-filesystem](https://github.com/norlab-ulaval/libpointmatcher/tree/leave-boost-filesystem)` branch with the updated dependency is green. I've merge PR #583 into PR #581 and waiting for build [#223
](http://132.203.26.125:8111/agents/overview).

**Pull request merged**
