### PR TITLE
refactor: Drop support for yaml-cpp old API

### LINKED ISSUE #42: Update to newer yaml-cpp API
Yaml-cpp has a new API since version 0.5.  Newer versions of Ubuntu now use yaml-cpp0.5 by default so libpointmatcher should be updated to use the new API.

### PR DESCRIPTION
**Pull request by aguenette**
fix #42

So, here's my attempt to upgrade libpointmatcher's `yaml-cpp` dependency to its new API.

As discuss in #42, `libpointmatcher` will no longer provides `yaml-cpp` sources in the contrib directory, which mean that Windows users will have to build and install `yaml-cpp` from [sources](https://github.com/jbeder/yaml-cpp).

I've followed [this tutorial](https://github.com/jbeder/yaml-cpp/wiki/Tutorial) to upgrade the API.

Changes:
- Use the new yaml-cpp API, i.e. version 0.5+.
- No longer provide sources in the contrib directory.

Tested on:
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] Windows

However, these changes need to be tested on Windows, so if a Windows user feels generous and is willing to test them, it would be greatly appreciated. 😄

Any suggestions are welcomed. Thanks!

### CODE REVIEW

**Comment by pomerlef** [comment]
add to white list

**Comment by pomerlef** [comment]
ok to test

**Comment by pomerlef** [comment]
Tests are failing on OSX

```
[ 72%] Linking CXX executable icp_customized
Undefined symbols for architecture x86_64:
  "YAML::Load(std::__1::basic_istream<char, std::__1::char_traits<char> >&)", referenced from:
      PointMatcher<float>::ICPChainBase::loadFromYaml(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in libpointmatcher.a(ICP.cpp.o)
      PointMatcher<double>::ICPChainBase::loadFromYaml(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in libpointmatcher.a(ICP.cpp.o)
      PointMatcher<float>::DataPointsFilters::DataPointsFilters(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in libpointmatcher.a(DataPointsFilter.cpp.o)
      PointMatcher<double>::DataPointsFilters::DataPointsFilters(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in libpointmatcher.a(DataPointsFilter.cpp.o)
  "YAML::detail::memory::create_node()", referenced from:
      YAML::Node::EnsureNodeExists() const in libpointmatcher.a(ICP.cpp.o)
  "YAML::detail::node_data::empty_scalar", referenced from:
      bool YAML::detail::node::equals<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, boost::shared_ptr<YAML::detail::memory_holder>) in libpointmatcher.a(ICP.cpp.o)
  "YAML::detail::node_data::mark_defined()", referenced from:
      YAML::detail::node::mark_defined() in libpointmatcher.a(ICP.cpp.o)
  "YAML::detail::node_data::end()", referenced from:
      PointMatcher<float>::ICPChainBase::loadFromYaml(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in libpointmatcher.a(ICP.cpp.o)
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const& PointMatcher<float>::ICPChainBase::createModulesFromRegistrar<PointMatcherSupport::Registrar<PointMatcher<float>::DataPointsFilter> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, YAML::Node const&, PointMatcherSupport::Registrar<PointMatcher<float>::DataPointsFilter> const&, std::__1::vector<std::__1::shared_ptr<PointMatcherSupport::Registrar<PointMatcher<float>::DataPointsFilter>::TargetType>, std::__1::allocator<std::__1::shared_ptr<PointMatcherSupport::Registrar<PointMatcher<float>::DataPointsFilter>::TargetType> > >&) in libpointmatcher.a(ICP.cpp.o)
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const& PointMatcher<float>::ICPChainBase::createModulesFromRegistrar<PointMatcherSupport::Registrar<PointMatcher<float>::OutlierFilter> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, YAML::Node const&, PointMatcherSupport::Registrar<PointMatcher<float>::OutlierFilter> const&, std::__1::vector<std::__1::shared_ptr<PointMatcherSupport::Registrar<PointMatcher<float>::OutlierFilter>::TargetType>, std::__1::allocator<std::__1::shared_ptr<PointMatcherSupport::Registrar<PointMatcher<float>::OutlierFilter>::TargetType> > >&) in libpointmatcher.a(ICP.cpp.o)
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const& PointMatcher<float>::ICPChainBase::createModulesFromRegistrar<PointMatcherSupport::Registrar<PointMatcher<float>::TransformationChecker> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, YAML::Node const&, PointMatcherSupport::Registrar<PointMatcher<float>::TransformationChecker> const&, std::__1::vector<std::__1::shared_ptr<PointMatcherSupport::Registrar<PointMatcher<float>::TransformationChecker>::TargetType>, std::__1::allocator<std::__1::shared_ptr<PointMatcherSupport::Registrar<PointMatcher<float>::TransformationChecker>::TargetType> > >&) in libpointmatcher.a(ICP.cpp.o)
      PointMatcher<double>::ICPChainBase::loadFromYaml(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in libpointmatcher.a(ICP.cpp.o)
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const& PointMatcher<double>::ICPChainBase::createModulesFromRegistrar<PointMatcherSupport::Registrar<PointMatcher<double>::DataPointsFilter> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, YAML::Node const&, PointMatcherSupport::Registrar<PointMatcher<double>::DataPointsFilter> const&, std::__1::vector<std::__1::shared_ptr<PointMatcherSupport::Registrar<PointMatcher<double>::DataPointsFilter>::TargetType>, std::__1::allocator<std::__1::shared_ptr<PointMatcherSupport::Registrar<PointMatcher<double>::DataPointsFilter>::TargetType> > >&) in libpointmatcher.a(ICP.cpp.o)
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const& PointMatcher<double>::ICPChainBase::createModulesFromRegistrar<PointMatcherSupport::Registrar<PointMatcher<double>::OutlierFilter> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, YAML::Node const&, PointMatcherSupport::Registrar<PointMatcher<double>::OutlierFilter> const&, std::__1::vector<std::__1::shared_ptr<PointMatcherSupport::Registrar<PointMatcher<double>::OutlierFilter>::TargetType>, std::__1::allocator<std::__1::shared_ptr<PointMatcherSupport::Registrar<PointMatcher<double>::OutlierFilter>::TargetType> > >&) in libpointmatcher.a(ICP.cpp.o)
      ...
  "YAML::detail::node_data::begin()", referenced from:
      PointMatcher<float>::ICPChainBase::loadFromYaml(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in libpointmatcher.a(ICP.cpp.o)
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const& PointMatcher<float>::ICPChainBase::createModulesFromRegistrar<PointMatcherSupport::Registrar<PointMatcher<float>::DataPointsFilter> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, YAML::Node const&, PointMatcherSupport::Registrar<PointMatcher<float>::DataPointsFilter> const&, std::__1::vector<std::__1::shared_ptr<PointMatcherSupport::Registrar<PointMatcher<float>::DataPointsFilter>::TargetType>, std::__1::allocator<std::__1::shared_ptr<PointMatcherSupport::Registrar<PointMatcher<float>::DataPointsFilter>::TargetType> > >&) in libpointmatcher.a(ICP.cpp.o)
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const& PointMatcher<float>::ICPChainBase::createModulesFromRegistrar<PointMatcherSupport::Registrar<PointMatcher<float>::OutlierFilter> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, YAML::Node const&, PointMatcherSupport::Registrar<PointMatcher<float>::OutlierFilter> const&, std::__1::vector<std::__1::shared_ptr<PointMatcherSupport::Registrar<PointMatcher<float>::OutlierFilter>::TargetType>, std::__1::allocator<std::__1::shared_ptr<PointMatcherSupport::Registrar<PointMatcher<float>::OutlierFilter>::TargetType> > >&) in libpointmatcher.a(ICP.cpp.o)
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const& PointMatcher<float>::ICPChainBase::createModulesFromRegistrar<PointMatcherSupport::Registrar<PointMatcher<float>::TransformationChecker> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, YAML::Node const&, PointMatcherSupport::Registrar<PointMatcher<float>::TransformationChecker> const&, std::__1::vector<std::__1::shared_ptr<PointMatcherSupport::Registrar<PointMatcher<float>::TransformationChecker>::TargetType>, std::__1::allocator<std::__1::shared_ptr<PointMatcherSupport::Registrar<PointMatcher<float>::TransformationChecker>::TargetType> > >&) in libpointmatcher.a(ICP.cpp.o)
      PointMatcher<double>::ICPChainBase::loadFromYaml(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in libpointmatcher.a(ICP.cpp.o)
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const& PointMatcher<double>::ICPChainBase::createModulesFromRegistrar<PointMatcherSupport::Registrar<PointMatcher<double>::DataPointsFilter> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, YAML::Node const&, PointMatcherSupport::Registrar<PointMatcher<double>::DataPointsFilter> const&, std::__1::vector<std::__1::shared_ptr<PointMatcherSupport::Registrar<PointMatcher<double>::DataPointsFilter>::TargetType>, std::__1::allocator<std::__1::shared_ptr<PointMatcherSupport::Registrar<PointMatcher<double>::DataPointsFilter>::TargetType> > >&) in libpointmatcher.a(ICP.cpp.o)
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const& PointMatcher<double>::ICPChainBase::createModulesFromRegistrar<PointMatcherSupport::Registrar<PointMatcher<double>::OutlierFilter> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, YAML::Node const&, PointMatcherSupport::Registrar<PointMatcher<double>::OutlierFilter> const&, std::__1::vector<std::__1::shared_ptr<PointMatcherSupport::Registrar<PointMatcher<double>::OutlierFilter>::TargetType>, std::__1::allocator<std::__1::shared_ptr<PointMatcherSupport::Registrar<PointMatcher<double>::OutlierFilter>::TargetType> > >&) in libpointmatcher.a(ICP.cpp.o)
      ...
  "YAML::detail::node_data::set_null()", referenced from:
      YAML::Node::EnsureNodeExists() const in libpointmatcher.a(ICP.cpp.o)
  "YAML::detail::node_data::size() const", referenced from:
      PointMatcherSupport::getNameParamsFromYAML(YAML::Node const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >&) in libpointmatcher.a(Registrar.cpp.o)
ld: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

make[2]: *** [examples/icp_customized] Error 1

make[1]: *** [examples/CMakeFiles/icp_customized.dir/all] Error 2

make: *** [all] Error 2
```

**Comment by xlla** [comment]
I have built it on jetson nano with yaml-cpp 0.5,  but failure with some tests.

`
[----------] Global test environment tear-down
[==========] 80 tests from 13 test cases ran. (87892 ms total)
[  PASSED  ] 78 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] Transformation.ComputeRigidTransformDataPoints3D
[  FAILED  ] Transformation.ComputeSimilarityTransformDataPoints3D
`

**Comment by aguenette** [comment]
Hi @xlla! On Ubuntu 18.04, all the tests pass. So, I'm not sure that the problem comes from the refactor of the yaml-cpp API. Have you tried to run the tests on the master branch (i.e. using the old yaml-cpp API)? If not, can you please try it and tell me if you get the same tests failure? It's just to be sure that it's not related with the changed from this branch. Thanks!

**Review by boxanm — APPROVED** [review]

**Pull request merged**
